version: '3.8'

# This file contains settings specific developing inside the containers

services:
  web:
    image: save-june-web-devcontainer
    build:
      context: web
      dockerfile: Dockerfile
      target: build-base
    volumes:
      - .:/workspace
    command: sleep infinity
    # Embedded devcontainer metadata
    x-devcontainer:
      post_create_command: npm install
      remote_user: web
      ports_attributes:
        "3000":
          label: Web Application
          on_auto_forward: notify
      features:
        common:
          username: web
          upgrade_packages: false
          non_free_packages: true
        chuxel/devcontainer-features/postgres:
          version: latest
          client_only: true
      tools:
        vscode:
          extensions:
            - dbaeumer.vscode-eslint
            - esbenp.prettier-vscode

  worker:
    image: save-june-worker-devcontainer
    build:
      context: worker
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/workspace
    command: sleep infinity
    # Embedded devcontainer metadata
    x-devcontainer:
      post_create_command: go get
      remote_user: worker
      portsAttributes:
        "8080":
          label: Worker
          on_auto_forward: notify
      features:
        common:
          username: worker
          upgrade_packages: false
          non_free_packages: true
        chuxel/devcontainer-features/postgres:
          version: latest
          client_only: true
        golang:
          version: "1.17.7"

  db:
    # We could also add a volume mount for the data like production.
    # But in this case, we'll just continue to reuse fresh test data
    # each time the postgres container is created.
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    # Embedded devcontainer metadata
    x-devcontainer:
      forward_ports: 
        - db:5432
      ports_attributes:
        "5432":
          label: Database
          on_auto_forward: silent

volumes:
  save-june-postgres-logs:
