version: '3.8'

# This file contains common configuraiton

services:
  web:
    image: save-june-web
    env_file: ./.env
    depends_on:
        - db

  worker:
    image: save-june-worker
    env_file: ./.env
    depends_on:
        - db

  db:
    image: postgres:14.1
    restart: unless-stopped
    env_file: ./.env
